version: 2

jobs:
  macos:
    macos:
      xcode: "9.2"
    steps:
      - checkout
      - run: swift build
      - run: swift test
  linux:
    docker:
      - image: codevapor/swift:4.1
    steps:
      - checkout
      - run: swift build
      - run: swift build -c release
      - run: export ENABLE_TESTS=true; swift test
workflows:
  version: 2
  tests:
    jobs:
      - linux
      # - macos
